### PR TITLE
STYLE: Move three internal helper functions into the unnamed namespace

### PR DESCRIPTION
**Pull request by N-Dekker**
Moved `writeJson`, `jsonRead`, and `addCoordinateTransformations` into the unnamed namespace of "itkOMEZarrNGFFImageIO.cxx".

Following C++ Core Guidelines, May 11, 2024, "Use an unnamed (anonymous) namespace for all internal/non-exported entities", http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf22-use-an-unnamed-anonymous-namespace-for-all-internalnon-exported-entities

### CODE REVIEW

**Comment by N-Dekker** [comment]
@dzenanz Some CI failures from _build-macos-arm-py (10)_ from https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/10683486429/job/29611671206?pr=72#step:8:198
```
Fetching Python frameworks
./macpython-download-cache-and-build-module-wheels.sh: line 81: /Users/svc-dashboard/D/P/ITKPythonPackage/scripts/macpython-install-python.sh: No such file or directory
Building module wheels
./macpython-download-cache-and-build-module-wheels.sh: line 85: /Users/svc-dashboard/D/P/ITKPythonPackage/scripts/macpython-build-module-wheels.sh: No such file or directory
```

Do you have a clue? At least I think they are unrelated to this pull request 😇

**Comment by dzenanz** [comment]
https://github.com/InsightSoftwareConsortium/ITKMontage suffers from the same error, I don't know what broke, or how. What are the chances for you to get to it this week?

**Comment by dzenanz** [comment]
I might get to it next week, unless someone else gets to it before then.

**Comment by dzenanz** [comment]
Ahh, someone else is already on it: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/283
What a pleasure 😄

**Comment by N-Dekker** [comment]
@dzenanz Can you please rerun the CI for _build-macos-arm-py_, for this pull request? Or otherwise just merge, and pray that it's okay 😺

**Comment by dzenanz** [comment]
The fix is ready. Let me apply it to this repo too.

**Comment by dzenanz** [comment]
I am hoping this should be enough to fix it: #73.

**Comment by dzenanz** [comment]
Rebasing on `main` should fix CI.

**Comment by N-Dekker** [comment]
Now _Build, test, package / build-windows-python-packages (8)_ fails, saying:
```

Invoke-WebRequest: D:\a\im\windows-download-cache-and-build-module-wheels.ps1:64
Line |
  64 |    Invoke-WebRequest -Uri "https://github.com/InsightSoftwareConsortiu …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (The response ended prematurely. (ResponseEnded))
Error: Process completed with exit code 1.
```

At https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/10744126899/job/29800364622?pr=72#step:8:86

Any clue?

**Comment by dzenanz** [comment]
That is most likely some network hiccup. We can re-run failed tests one the others finish running.

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
