### PR TITLE
ENH: Adjust to new version of tensorstore: zip renamed into zip_memory

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by tbirdso — APPROVED** [review]
Looks reasonable. Could you please confirm whether this change is intended to be merged before or alongside an update to the underlying Tensorstore?

**Comment by dzenanz** [comment]
Master is now at [Squash of 1222a146a52ea8352b1adf4e435eeb740134f1d2](https://github.com/InsightSoftwareConsortium/tensorstore/commit/9d45c2f3aa13618d215d3370ef09d089986215c7). Squashing the additional commits was required due to [introduction of `zip` kvstore](https://github.com/google/tensorstore/commit/45565464b9f9e2567144d780c3bef365ee3c125a) in the official repo, and massive number of merge conflicts without squashing. [1222a146a52ea8352b1adf4e435eeb740134f1d2](https://github.com/InsightSoftwareConsortium/tensorstore/commit/1222a146a52ea8352b1adf4e435eeb740134f1d2) is available via branch [beforeRebasingOnOfficialZip](https://github.com/InsightSoftwareConsortium/tensorstore/tree/beforeRebasingOnOfficialZip).

The rename from `zip` to `zip_memory` must be done at the same time in here and in https://github.com/InsightSoftwareConsortium/tensorstore, unless we want to use branch names - which is also reasonable.

**Comment by tbirdso** [comment]
> The rename from zip to zip_memory must be done at the same time in here and in https://github.com/InsightSoftwareConsortium/tensorstore, unless we want to use branch names - which is also reasonable.

Thanks for the explanation, it makes sense to move forward with the update to `zip_memory` here.

I am in favor of pinning the `InsightSoftwareConsortium/tensorstore` to the latest commit hash instead of `master`. From my understanding of the explanation above, `ITKIOOMEZarrNGFF@master` currently will not build because it pulls from `tensorstore@master` which has been force-updated. Pinning to a commit hash would guard against future breakage and allow us to update ITKIOOMEZarrNGFF at our own pace independent of future rebases or refactoring in the tensorstore fork.

Do you agree? If so, would you be willing to do that in this PR to help indicate in commit history that these changes are linked to a change in the `tensorstore` fork structure?

**Comment by tbirdso** [comment]
i.e. I suggest updating this line: https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/blob/master/src/CMakeLists.txt#L23

**Comment by dzenanz** [comment]
I repointed master back to [aaf8b85](https://github.com/InsightSoftwareConsortium/tensorstore/commit/aaf8b85ad123e10482f6917f9880d33972814b53), to allow proper building of any older version.

**Comment by tbirdso** [comment]
> I repointed master back to [aaf8b85](https://github.com/InsightSoftwareConsortium/tensorstore/commit/aaf8b85ad123e10482f6917f9880d33972814b53), to allow proper building of any older version.

Sure, that's fine. It might be worthwhile to start an issue there for discussion on how we can maintain releases for later reference while clearly directing users to the most recent version.

**Comment by dzenanz** [comment]
We should keep it at master for a few months at least. Starting with `0.2.0` (this PR), we will have hashes which makes it easy to see which version is intended to be used, and we can have master just be the most recent version we have.

**Comment by dzenanz** [comment]
Linux compile error reported: https://github.com/google/tensorstore/issues/112.

**Comment by thewtex** [comment]
Please keep `InsightSoftwareConsortium/tensorstore` `master` consistent with upstream `master`. Then, push to branches with the zip memory store patches with a name like `ITKIOOMEZarrNGFF-2023-09-06-abc123abc` where `2023-09-06-abc123abc` is the date and commit of upstream `master`. These branches should not have any merge commits -- they are created by rebasing additional patches on upstream. The update the commit sha here to be the value of the HEAD of `ITKIOOMEZarrNGFF-2023-09-06-abc123abc`. If we need to make additions to our patches then add `-1`, `-2`, etc. For example `ITKIOOMEZarrNGFF-2023-09-06-abc123abc-1`. This ensures that we do not deviate from upstream, patches can be cleanly push upstream, rebases can be made without conflicts, and we reference a commit that will always be present in the repository.

**Comment by dzenanz** [comment]
Done in #57.

**Comment by dzenanz** [comment]
Another snag with tensorstore: https://github.com/google/tensorstore/issues/113.

**Pull request merged**
