### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by dzenanz**
Preparation to do a GitHub tagging + release to test automated package building and deployment to PyPI.

### CODE REVIEW

**Comment by dzenanz** [comment]
Inspired by [warnings](https://open.cdash.org/viewBuildError.php?type=1&buildid=8414157) of the style _[KWStyle/kwsCheckLineLength.cxx:24](https://github.com/InsightSoftwareConsortium/ITK/blob/master/KWStyle/kwsCheckLineLength.cxx#L24):3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]_, I am updating KWSys in https://github.com/InsightSoftwareConsortium/ITK/pull/3880. This was easy to do, but what is probably needed is an update to https://github.com/Kitware/KWStyle.

@tbirdso do you know why this only occurs here? https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/blob/5de5a18bd34c267c3b1a275d88fb3b0f1c1965cd/.github/workflows/build-test-cxx.yml#L39 also uses `macos-12`, so other remote modules should be affected.

**Comment by tbirdso** [comment]
@dzenanz It looks like the warning also occurs in the most recent ITKSplitComponents build:

https://open.cdash.org/viewBuildError.php?type=1&buildid=8414064

Perhaps this also has to do with the recent reusable workflow update to use CMake 3.24?

**Comment by dzenanz** [comment]
I doubt it. This PR doesn't touch CMake version, and this repo already uses CMake 3.24. This is more likely coming from macOS 11 to 12 switch, which uses a newer version of XCode/clang.

**Comment by tbirdso** [comment]
> This is more likely coming from macOS 11 to 12 switch, which uses a newer version of XCode/clang.

Ah, that makes sense. I'm testing an additional step in ITKRemoteModuleBuildTestPackageAction to fix the XCode version in cxx testing in the same way that we do for building Python wheels. Results will be available at https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3969955914/jobs/6805099767

**Comment by dzenanz** [comment]
And that build is green, the one in this PR isn't 😞

**Comment by tbirdso** [comment]
@dzenanz In the build I linked I have downgraded the XCode version to 13.2 which is what we use for building ITK Python tarballs for distribution. I believe you are correct that warnings result from using XCode 14 for building. That downgrade will not directly address the problem, but will make the external module build process more closely align to the ITK core build process.

**Pull request merged**
